[package]
name = "errlog"
version = "0.1.0"
edition = "2021"
authors = ["ikey4u <pwnkeeper@gmail.com>"]
description = "A simple error logger based on anyhow"
license = "MIT"
repository = "https://github.com/ikey4u/errlog"
keywords = ["log", "anyhow"]

[dependencies]
anyhow = "1.0.43"
